---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qinspect/public_html
    - export APIPATH=/home/qinspect/api_app
    - /bin/cp -R frontend/dist/spa/* $DEPLOYPATH
    - /bin/cp -R api/* $APIPATH
    - /bin/mkdir -p $APIPATH/tmp
    - /bin/touch $APIPATH/tmp/restart.txt
